apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: integrasjonspunkt-difi-nais
  namespace: default
  labels:
    team: teamdokumenthandtering
spec:
  image: "repo.adeo.no:5443/integrasjonspunkt-difi-nais/integrasjonspunkt-difi-nais:@@VERSION@@"
  team: teamdokumenthandtering
  replicas:
    min: 1
    max: 1
  port: 8080
  liveness:
    path: /manage/info
    initialDelay: 20
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /manage/health
    initialDelay: 20
    periodSeconds: 5
    failureThreshold: 10
  prometheus:
    enabled: false
    path: /prometheus
  istio:
    enabled: false
  ingresses:
    enabled: true
  vault:
    enabled: true
  webproxy: true
  resources:
    limits:
      cpu: 2000m
      memory: 4096Mi
    requests:
      cpu: 100m
       memory: 1024Mi