apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: integrasjonspunkt
  namespace: default
  labels:
    team: {{ team }}
spec:
  image: "navikt/integrasjonspunkt-difi-nais:{{version}}"
  replicas:
    min: 1
    max: 1
  port: 8080
  liveness:
#    path: /manage/info
    path: /swagger-ui.html
    initialDelay: 20
    periodSeconds: 5
    failureThreshold: 10
  readiness:
#    path: /manage/health
    path: /swagger-ui.html
    initialDelay: 20
    periodSeconds: 5
    failureThreshold: 10
  prometheus:
    enabled: false
    path: /prometheus
  ingresses:
     - {{INGRESS}}
  vault:
    enabled: true
    paths:
      - kvPath: {{VIRKSOMHETSSERTIFIKAT_VAULT_PATH}}
        mountPath: /var/run/secrets/nais.io/virksomhetssertifikat
  resources:
    limits:
      cpu: 2000m
      memory: 4096Mi
    requests:
      cpu: 100m
      memory: 1024Mi
  webproxy: true
  env:
  {{#each env}}
    - name: {{@key}}
      value: "{{this}}"
  {{/each}}
